Ewikis/apps/wiki/urls.py
from django.conf.urls.defaults import patterns, include, url
urlpatterns = patterns('apps.wiki.views',
	url(r'^(\w+)/$','wiki'),
	url(r'^(\w+)/(\d+)/edit/$','editsection'),
	url(r'^(\w+)/(\d+)/move/$','movesection'),
	url(r'^(\w+)/deletesection/$','deletesection'),
	url(r'^(\w+)/addtext/$','addtext'),
	url(r'^(\w+)/addimage/','addimage'),
	url(r'^(\w+)/like/$','likewiki'),
	url(r'^(\w+)/editwiki/$','editwiki'),
	url(r'^(\w+)/deletewiki/$','deletewiki'),
	url(r'^wiki/main/$','main'),
	url(r'^wiki/create/$','createwiki'),
	url(r'^print/(\w+)/$','printwiki'),
	url(r'^wiki/pdfexport/(\w+)/$','pdfExport'),
	url(r'^dir/(\w+)','subject'),
	url(r'^wiki/help/$','help'),
	url(r'^wiki/search/$','search'),
)

Ewikis/urls.py
from django.conf.urls.defaults import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
import settings

urlpatterns = patterns('',
	#Thai Linh
	url(r'^', include('apps.userprof.urls')),
	url(r'^',include('apps.wiki.urls')),

	url(r'^wiki/admin/',include(admin.site.urls)),
	(r'^static/(?P<path>.*)$','django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
	(r'^media/(?P<path>.*)$','django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/favicon.ico'}),	

)

Ewikis/apps/wiki/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
GRADE_LEVEL_CHOICE = (
                      ('KINDERGARTEN','Kindergarten/Pre-K'),
                      ('1G','1st Grade'),
                      ('2G','2nd Grade'),
                      ('3G','3rd Grade'),
                      ('4G','4th Grade'),
                      ('5G','5th Grade'),
                      ('6G','6th Grade'),
                      ('7G','7th Grade'),
                      ('8G','8th Grade'),
                      ('9G','9th Grade'),
                      ('10G','10th Grade'),
                      ('11G','11th Grade'),
                      ('12G','12th Grade'),
                      ('COLLEGE','College'),
                      ('OCCUPTIONAL','Occupational'))
SUBJECT_CHOICE = (
					('ART','Art'),
					("BUSINESS",'Business and Economics'),
					('COMPUTERS','Computer Science'),
					('GEOGRAPHY','Geography'),
					('History',(
								('CHINA','China'),
								('VIETNAM',u'Việt Nam'),
								('WORLD', 'World'),
								)
					),
					('MUSIC','Music'),
					('MOVIE','Movie'),
					('Math',(
								('ALEGEBRA','Alegebra'),
								('ARITHMETIC','Arithmetic'),
								('CALCULUS', 'Calculus'),
								('GEOMETRY','Geometry'),
								('STATISTICS', 'Statistics'),
								)
					),
					('Foreign Language',(
								('ENGLISH','English'),
								('VIETNAMESE','Vietnamese'),
								('CHINESE', 'Chinese'),
								('SPANISH','Spanish'),
								)
					),
					
					('Science',(
								('BIOLOGY','Biology'),
								('CHEMISTRY','Chemistry'),
								('EARTHSICENCE', 'Earth Science'),
								('PHYSICS','Physics'),
								('PSYCHOLOGY', 'Psychology'),
								('MEDICINE','Medicine'),
								)
					),
					('RELIGION','Religion'),
					('OTHER','Other')
				)    
LESSON_TYPE_CHOICE = (
                      ('TEACHER','Teacher Lesson Plan'),
                      ('STUDENT','Student Study Guide'),
                      ('ASSIGNMENT','Assignment/Project'),
                      ('CLASSROOM_INFORMATION','Classroom Information'),
                	  ('OTHER','Other')
)
	
class Wiki(models.Model):
	user = models.ForeignKey(User, related_name = 'user')
	title = models.CharField('Title',max_length = 80,error_messages={'required': 'Please enter your name'})
	titleid = models.CharField('Title ID',max_length = 80, primary_key = True)
	description = models.CharField('Description', max_length = 400)
	gradelevel = models.CharField('Grade Level', choices = GRADE_LEVEL_CHOICE, max_length = 20)
	subject = models.CharField('Subsject', choices = SUBJECT_CHOICE, max_length = 30)
	lessontype = models.CharField('Lesson Type', choices = LESSON_TYPE_CHOICE, max_length = 30)
	like = models.IntegerField(default = 0)
	userlike = models.ManyToManyField(User,blank=True,null=True)
	def __unicode__(self):
		return self.title
		
class Section(models.Model):
	wiki = models.ForeignKey(Wiki)
	title = models.CharField('Title', max_length = 40)
	content = models.TextField("Content",error_messages={'blank': 'NotNull','required': "My custom error"})
	content_markdown = models.TextField("Content Markdown")
	def __unicode__(self):
		return self.title
	def save(self, *args, **kargs):
		import markdown
		md = markdown.Markdown(extensions =
								['fenced_code','codehilite','wikilinks','mdx_video','urlize','tables',
									'nl2br',],
							  )
		self.content_markdown = md.convert(self.content)
		super(Section,self).save(*args, **kargs)
class Image(models.Model):
	user = models.ForeignKey(User)
	title = models.CharField('Title', max_length = 40)
	photo = models.ImageField(upload_to = 'photos')
	def __unicode__(self):
		return self.title

Ewikis/apps/wiki/forms.py
from django import forms
from django.forms import ModelForm

from apps.wiki.models import *

class TextForm(ModelForm):
	class Meta:
		model = Section
		fields =('title', 'content')
		widgets = {
			'content': forms.Textarea(attrs = {'cols':10, 'rows': 10}),
			}
	def __init__(self, *args, **kwargs):
		super(TextForm, self).__init__(*args, **kwargs)
		self.fields['title'].widget.attrs['class'] = 'span6'
		self.fields['content'].widget.attrs['class'] = 'span10'
class CreateWikiForm(ModelForm):
	class Meta:
		model = Wiki
		fields = ('title','description', 'gradelevel','subject','lessontype')
		widgets = {
			'description': forms.Textarea(attrs = {'cols':40, 'rows': 6,'style':'width:400px','placeholder':'Description for yours wiki'}),
			}

	def clean_description(self):
		des = self.cleaned_data['description']
		if len(des) < 50:
			raise forms.ValidationError('Your description is smaller than 50 characters')
		return des
	def clean_title(self):
		title = self.cleaned_data['title']
		if len(title) < 3:
			raise forms.ValidationError('Your title is smaller than 3 characters')
		return title
	def __init__(self, *args, **kwargs):
		super(CreateWikiForm, self).__init__(*args, **kwargs)
		self.fields['title'].widget.attrs['style'] = 'width:400px; font-weight:bold; font-size:16px'
		self.fields['title'].error_messages['required'] = 'Type yours title'
		self.fields['description'].error_messages['required'] = 'Make some descriptions for yours wiki'
		self.fields['gradelevel'].error_messages['required'] = 'Choice yours Grade Level'
		self.fields['subject'].error_messages['required'] = 'Choice Subject for wiki'
		self.fields['lessontype'].error_messages['required'] = 'What is the lesson type for your wiki?'

class ImageForm(ModelForm):
	class Meta:
		model = Image
		fields = ('title','photo')
	def clean_photo(self):
		photo = self.cleaned_data['photo']
		if photo.size > 2 * 2 ** 20:
			raise forms.ValidationError('Size photo too big, the maximun size is 2MB')
		return photo
	def __init__(self, *args, **kwargs):
		super(ImageForm, self).__init__(*args, **kwargs)
		self.fields['title'].error_messages['required'] = 'Type yours title'
		self.fields['photo'].error_messages['required'] = 'Please upload a photo' 
   

Ewikis/apps/wiki/views.py
from apps.wiki.models import *
from apps.wiki.forms import *
from apps.wiki.wiki import *
from apps.userprof.models import *

from itertools import chain

from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.template import Context, RequestContext, loader
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response, get_object_or_404
from django.db.models import Q
from pure_pagination.paginator import Paginator

import pdfcrowd
import re
import settings

def pdfExport(request,titleid):
	wiki = get_object_or_404(Wiki,pk = titleid)
	section = wiki.section_set.all()
	t = loader.get_template('wiki/printwiki.html')
	var = RequestContext(request,{
		'wiki': wiki,
		'section': section,
	})
	html = HttpResponse(t.render(var))
	try:
		client = pdfcrowd.Client("locbh", "eb76e893ef32482f3ccc1e159af67977")
		client.setPageWidth(595)
		client.setPageHeight(841)
		pdfhtml = client.convertHtml(html)
		urlconvert = 'http://wikis.herokuapp.com/print/' + titleid
		pdf = client.convertURI(urlconvert)
		response = HttpResponse(mimetype="application/pdf")
		response["Cache-Control"] = "no-cache"
		response["Accept-Ranges"] = "none"
		response["Content-Disposition"] = "attachment; filename=%s.pdf"%(titleid)
		response.write(pdf)
	except pdfcrowd.Error, why:
		response = HttpResponse(mimetype="text/plain")
		response.write(why)
	return response
def subject(request,subject):
	wikisubject = filterWiki(request,subject,Wiki)
	var = RequestContext(request,{
		'wikisubject': wikisubject,
		'subject':subject,
		'form':CreateWikiForm(),

	})
	return render_to_response("wiki/dir/subject.html",var)
def help(request):
	return render_to_response("wiki/about.html",RequestContext(request))
@login_required
def search(request):
	query = request.GET.get('query', '')
	query = query.strip()
	result = []
	if query:
		wiki= Wiki.objects.filter(Q(title__icontains= query)).order_by('-like')
		result = list(chain(wiki))
		for q in query.split():
			sub = list(chain(Wiki.objects.filter(Q(title__icontains= q))))
			for wi in sub:
				if not wi in result:
					result.append(wi)
					
	wiki = Paginator(result,5,request=request).page(request.GET.get('page',1))
	var = RequestContext(request,{
		'query':query,
		'wiki': wiki,
		'form': CreateWikiForm(),
    })
	return render_to_response("wiki/search.html",var)

def main(request):
	wiki = Wiki.objects.all().order_by('-like')[:5]
	wikiArt = Wiki.objects.filter(Q(subject='ART')).order_by('-like')[:5]
	wikiMovie = Wiki.objects.filter(Q(subject='MOVIE')).order_by('-like')[:5]
	wikiMusic = Wiki.objects.filter(Q(subject='MUSIC')).order_by('-like')[:5]
	wikiEconomic = Wiki.objects.filter(Q(subject='BUSINESS')).order_by('-like')[:5]
	wikiComputerScience = Wiki.objects.filter(Q(subject='COMPUTERS')).order_by('-like')[:5]
	wikiGeography = Wiki.objects.filter(Q(subject='GEOGRAPHY')).order_by('-like')[:5]
	wikiReligion = Wiki.objects.filter(Q(subject='RELIGION')).order_by('-like')[:5]
	wikiOther = Wiki.objects.filter(Q(subject='OTHER')).order_by('-like')[:5]

	wikiMath = Wiki.objects.filter(
				Q(subject='ALEGEBRA')|
				Q(subject='ARITHMETIC')|
				Q(subject='CALCULUS')|
				Q(subject='GEOMETRY')|
				Q(subject='STATISTICS')
				).order_by('-like')[:5]
	wikiHistory = Wiki.objects.filter(
			Q(subject='CHINA')|
			Q(subject='VIETNAM')|
			Q(subject='WORLD')
			).order_by('-like')[:5]
	wikiLanguage = Wiki.objects.filter(
			Q(subject='CHINESE')|
			Q(subject='VIETNAMESE')|
			Q(subject='ENGLISH')|
			Q(subject='SPANISH')
			).order_by('-like')[:5]
	wikiScience = Wiki.objects.filter(
			Q(subject='BIOLOGY')|
			Q(subject='CHEMISTRY')|
			Q(subject='EARTHSICENCE')|
			Q(subject='PHYSICS')|
			Q(subject='PSYCHOLOGY')|
			Q(subject='MEDICINE')
			).order_by('-like')[:5]


	var = RequestContext(request,{
		'wiki': wiki,
		'wikiArt' : wikiArt,
		'wikiMovie' : wikiMovie,
		'wikiMusic' : wikiMusic,
		'wikiEconomic': wikiEconomic,
		'wikiComputerScience' : wikiComputerScience,
		'wikiGeography': wikiGeography,
		'wikiReligion' : wikiReligion,
		'wikiOther' : wikiOther,
		'wikiMath' : wikiMath,
		'wikiHistory' : wikiHistory,
		'wikiLanguage' : wikiLanguage,
		'wikiScience' : wikiScience,
		'form':CreateWikiForm(),
	})
	return render_to_response("wiki/main.html",var)

def wiki(request,title_id):
	wiki = get_object_or_404(Wiki,pk = title_id)
	allwiki = Wiki.objects.filter(user = wiki.user)
	profile = get_object_or_404(Profile, user=wiki.user)
	userlike = wiki.userlike.filter(username = request.user.username)
	section = wiki.section_set.all()
	var = RequestContext(request,{
		'wiki': wiki,
		'section': section,
		'userlike': userlike,
		'allwiki': allwiki,
		'profile': profile,
		'form':CreateWikiForm(),
	
	})
	return render_to_response('wiki/wiki.html', var)
def printwiki(request,titleid):
	wiki = get_object_or_404(Wiki,pk=titleid)
	section = wiki.section_set.all()
	var = RequestContext(request,{
	'wiki': wiki,
	'section': section,
	})
	return render_to_response('wiki/printwiki.html', var)

@login_required	
def addtext(request, title_id):
	wiki = get_object_or_404(Wiki,pk = title_id)
	allwiki = Wiki.objects.filter(user = wiki.user)
	userlike = wiki.userlike.filter(username = request.user.username)
	if request.method == 'POST':
		textform = TextForm(request.POST)
		if textform.is_valid():
			inp = textform.cleaned_data
			wiki.section_set.create(title = inp['title'],
									content = inp['content'],
									content_markdown = inp['content'])
			return HttpResponseRedirect("/"+ title_id)
		textform = TextForm()
	else:
		textform = TextForm()
	var = RequestContext(request,{
			'textform':textform,
			'wiki': wiki,	
			'allwiki':allwiki,
			'userlike':userlike,
			})
	return render_to_response('wiki/addtext.html',var)

@login_required	
def addimage(request, title_id):
	wiki = Wiki.objects.get(pk = title_id)
	allwiki = Wiki.objects.filter(user = wiki.user)
	userlike = wiki.userlike.filter(username = request.user.username)
	image = None
	
	if request.method == 'POST':
		imageform = ImageForm(request.POST, request.FILES)
		if imageform.is_valid():
			title = imageform.cleaned_data['title']
			uploadphoto = imageform.cleaned_data['photo']
			image = Image.objects.create(
				user = request.user,
				photo = uploadphoto,
				title = title
			)
			image.save()
			content_image_markdown = '![%s](%s)'% (image.photo.size, image.photo.url)
			wiki.section_set.create(
					title = title, 
					content = content_image_markdown,
					content_markdown = content_image_markdown
				)
			return HttpResponseRedirect("/"+ title_id)
	else:
		imageform = ImageForm()
	var = RequestContext(request,{
		'imageform':imageform,
		'wiki':wiki,
		'allwiki':allwiki,
		'userlike':userlike
		})
	return render_to_response('wiki/addimage.html',var)
@login_required
def editsection(request, title_id, sec_id):
	wiki = Wiki.objects.get(pk = title_id)
	allwiki = Wiki.objects.filter(user = wiki.user)
	section = get_object_or_404(Section, pk = sec_id)
	wiki = get_object_or_404(Wiki, pk = title_id)
	userlike = wiki.userlike.filter(username = request.user.username)

	if request.method == 'POST':
		textform = TextForm(request.POST)
		if textform.is_valid():
			inp = textform.cleaned_data
			section.title = inp['title']
			section.content = inp['content']
			section.content_markdown = inp['content']
			section.save()
			return HttpResponseRedirect("/"+ title_id)
	else: 
		textform = TextForm(instance=Section.objects.get(pk = sec_id))
	var = RequestContext(request,{
			'textform':textform,
			'wiki': wiki,
			'allwiki':allwiki,
			'userlike':userlike,
			})
	return render_to_response('wiki/edittext.html',var)

@login_required	
def deletesection(request, title_id):
	if 'id' in request.GET:
		sec_id = request.GET['id']
		section = Section.objects.get(pk = sec_id)
		section.delete()
	return HttpResponseRedirect("/"+ title_id)
	
@login_required	
def createwiki(request):
	if request.method == 'POST':
		form = CreateWikiForm(request.POST)
		if form.is_valid():
			inp = form.cleaned_data
			title_id = inp['title'].lower()
			title_id = ''.join(re.compile(r'\W+').split(title_id))
			check_titleid  = Wiki.objects.all()
			# check link to access wiki
			for check in check_titleid:
				if title_id == check.titleid:
					title_id = title_id + '_1'
			wiki = Wiki(
				user = request.user,
				title = inp['title'],
				titleid = title_id,
				description = inp['description'],
				gradelevel = inp['gradelevel'],
				subject = inp['subject'],
				lessontype = inp['lessontype'],
				like = 0,
				)
			wiki.save()
			return HttpResponseRedirect("/"+ title_id)
	else:
		error = True;
		form = CreateWikiForm()
	var = RequestContext(request,{'form':form,})
	return render_to_response('wiki/createwiki.html',var)
@login_required	
def editwiki(request, title_id):
	wiki = get_object_or_404(Wiki,pk = title_id)
	section = wiki.section_set.all()
	temp_title_id  = title_id
	if request.method == 'POST':	
		form = CreateWikiForm(request.POST)
		if form.is_valid():
			inp = form.cleaned_data
			title_id = inp['title'].lower()
			title_id = ''.join(re.compile(r'\W+').split(title_id))
			check_titleid  = Wiki.objects.all()
			for check in check_titleid:
				if title_id == check.titleid:
					if title_id != temp_title_id:
						title_id = title_id + '_1'
			wiki.titleid = title_id
			wiki.title = inp['title']
			wiki.description = inp['description']
			wiki.gradelevel = inp['gradelevel']
			wiki.subject = inp['subject']
			wiki.lessontype = inp['lessontype']
			wiki.save()
			if title_id != temp_title_id:
				for sec in section:
					wiki.section_set.create(title = sec.title,content = 			 
					sec.content, content_markdown = sec.content_markdown)
				wikiold = get_object_or_404(Wiki,pk = temp_title_id)
				wiki.like = wikiold.like
				for user in wikiold.userlike.all():
					wiki.userlike.add(user)
				wikiold.delete()
			wiki.save()
			return HttpResponseRedirect("/"+ wiki.titleid)
	else:

Ewikis/templates/wiki/addimage.html
{% extends "base.html" %}
{% load markup%}
{% load gravatar %}
{%block title%}{{wiki.title}}{%endblock title%}
{%block userinfo%}
<div class="thumbnail">
	<div style="height: 60px;">
		<img style="float:left;margin:10px 10px; border-radius: 3px 3px;" height="40" src="{% gravatar_url wiki.user.email %}" width="40"/>
		<div style="float:left; margin-top:10px">
			<h6> <a style="text-decoration: none" href="/user/{{wiki.user}}">{{wiki.user.first_name}} {{wiki.user.last_name}}</a></h6>
			<div class="like-results">
				{% include "wiki/wiki_like.html" %}
			</div>
		</div>
	</div>
</div><br>

{%endblock userinfo%}
{% block moreinfor %}
<div class="thumbnail">
	<li class="nav-header"><h5>More form {{wiki.user.first_name}} {{wiki.user.last_name}}</h5></li>
	<ul class="nav nav-list">
		{% for wi in allwiki  %}
		<li class="{% ifequal request.path "{{wi.titleid}}" %}active{% endifequal %}"><a href="/{{wi.titleid}}"><i class="icon-file {% ifequal request.path "{{wi.titleid}" %}icon-white{% endifequal %}"></i>{{wi.title}}</a></li>
		{% endfor %}
	</ul>
</div>
{% endblock moreinfor %}

{%block breadcrumbs%}
	<span class="divider">&raquo</span>
  	<li>{{wiki.title}}</li>
{%endblock breadcrumbs%}
{% block content%}
	{% include "wiki/addimage_modal.html" %}
{% endblock content %}

Ewikis/templates/wiki/addimage_modal.html
{% for field in imageform.visible_fields %}
    {% for err in field.errors %}
    <li class="alert alert-error fade in": style="margin:10px 0px; list-style: none;">{{ err }}</li>
    {% endfor %}
{% endfor %}
<form action="/{{wiki.titleid}}/addimage/" method="post" enctype="multipart/form-data">{% csrf_token %}
	<input class="span5" style="font-size: 18px" id="id_title" type="text" name="title" maxlenght="80" placeholder = "Title">
	    <div class="fileupload fileupload-new" data-fileupload="image">
            <div class="fileupload-new thumbnail" style="max-width: 400px; height: 200px;"><img src="http://www.placehold.it/400x200/EFEFEF/AAAAAA&text=no+image" /></div>
            <div class="fileupload-preview fileupload-exists thumbnail" style="margin:3px 3px;max-width: 400px; max-height: 200px;"></div>
            <div style="margin-top:10px">
                <span class="btn btn-success btn-file"><i class="icon-plus icon-white"> </i> <span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span><input type="file" name="photo" id="id_photo"></span>
                <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload"><i class="icon-remove icon-white"> </i> Remove</a>
                <button class = "btn btn-primary fileupload-exists">
    	           <i class="icon-upload icon-white"> </i> Upload
    	           <input style="opacity:0;width:20px; height: 10px" type="submit" value="Upload" />
                </button>
            </div>
        </div>				
</form>

Ewikis/templates/wiki/addtext.html
{% extends "base.html" %}
{% load markup%}
{% load gravatar %}
{%block title%}{{wiki.title}}{%endblock title%}

{%block userinfo%}
<div class="thumbnail">
    <div style="height: 60px;">
        <img style="float:left;margin:10px 10px; border-radius: 3px 3px;" height="40" src="{% gravatar_url wiki.user.email %}" width="40"/>
        <div style="float:left; margin-top:10px">
            <h6> <a style="text-decoration: none" href="/user/{{wiki.user}}">{{wiki.user.first_name}} {{wiki.user.last_name}}</a></h6>
            <div class="like-results">
                {% include "wiki/wiki_like.html" %}
            </div>
        </div>
    </div>
</div><br>
{%endblock userinfo%}}
{% block moreinfor %}
<div class="thumbnail">
    <li class="nav-header"><h5>More from {{wiki.user.first_name}} {{wiki.user.last_name}}</h5></li>
    <ul class="nav nav-list">
        {% for wi in allwiki  %}
            <li class="{% ifequal request.path "{{wi.titleid}}" %}active{% endifequal %}"><a href="/{{wi.titleid}}"><i class="iconic-book-alt" style="color:#000"></i> {{wi.title}}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock moreinfor %}

{%block breadcrumbs%}
	<span class="divider">&raquo</span>
  	<li>{{wiki.title}}</li>
{%endblock breadcrumbs%}
{% block content%}
	{% include "wiki/addtext_modal.html" %}
{% endblock content %}

Ewikis/templates/wiki/addtext_modal.html
{% for field in textform.visible_fields %}
    {% for err in field.errors %}
    <li class="alert alert-error fade in": style="margin:10px 10px; list-style: none;">{{ err }}</li>
    {% endfor %}
{% endfor %}
<form name="Add text" action = "/{{wiki.titleid}}/addtext/" method ='POST'>
	{% csrf_token %} 
	<div class="addtext" >
    <div class= "row-fluid">
      <div class="span12">
        <input id="id_title" style="height:22px;" type="text" name="title" maxlength="40" placeholder="Title" />
      </div>
    </div>
    <div class= "row-fluid">
      <div class="span12">
	      <textarea rows="9" name="content" id="id_content" cols="100" class="span12"></textarea>
      </div>
    </div>
  </div>
  <div style="margin-top:10px">
    <a><input class = "btn" type="submit" value = "Save"/></a>
    <a href = "/{{wiki.titleid}}"class = "btn btn-danger" >Cancel</a>
  </div>
</form>

Ewikis/templates/wiki/createwiki.html
{% extends "base.html"%}

{%block title%}Create Wikis{%endblock title%}
{%block option%}
	{%if not user.is_authenticated%}
	<p style="color:#999">Create and share free online wikis for your classroom in just minutes:<br/> 
	<div class="btn-group">
	<a href="/user/register" class="btn btn-info">Signup</a>
	<a href="/wiki/login" class="btn">Login</a>
	</div>
	{% else %}
	<div id="modalWiki" class="modal hide fade in" style="width:auto; top:42%">
            <div class="modal-header">
              <a class="close" data-dismiss="modal">×</a>
              <h3>Create new wiki</h3>
            </div>
            <div class="modal-body">
          	{% include "wiki/createwiki_modal.html" %}
          	</div>
    </div>
    <div class="row-fluid">
    <a data-toggle="modal" href="#modalWiki" class="span12 btn btn-large"><i class="iconic-book-alt2" style="color:#0088cc; margin:20px 0px"> </i>New Wiki</a>
    </div></br>
	{%endif%}
{%endblock option%}
{% block moreinfor %}
	{% include "wiki/sidebar.html" %}
{% endblock moreinfor %}

{%block breadcrumbs%}
  <li class = "disabled"><span style="font-size:14px;color:#999" >Create wiki<span/></li>
{%endblock breadcrumbs%}

{% block content%}
<div class="row-fluid">
  <div class="span8">
  {% for field in form.visible_fields %}
      {% for err in field.errors %}
      <li class="alert alert-error fade in": style="list-style: none;">{{ err }}</li>
      {% endfor %}
  {% endfor %}
    {% include "wiki/createwiki_modal.html" %}
  </div>
</div>
{% endblock %}

Ewikis/templates/wiki/createwiki_modal.html
<form name="Edit" action = "/wiki/create/" method ='POST'>
	{% csrf_token %}
<table>
    <tbody>
   		<tr>
        	<td class="label_create_wiki">Title</td>
        	<td>{{form.title}}</td>
      	</tr>
      	<tr>
       		<td style=""></td>
        	<td>{{form.description}}</td>
      	</tr>
        <tr>
       		<td class="label_create_wiki">Grade Level </td>
        	<td>{{form.gradelevel}}</td>
      	</tr>
        <tr>
       		<td class="label_create_wiki">Subject</td>
        	<td>{{form.subject}}</td>
      	</tr>
        <tr>
       		<td class="label_create_wiki">Lesson type </td>
        	<td>{{form.lessontype}}</td>
      	</tr>
    </tbody>
</table>
    <button class = "btn btn-createwiki">
    	<i class="iconic-book-alt2" style="color:#0088cc"> </i> Create wiki
    	<input style="opacity:0;width:20px; height: 18px" type="submit" value="post" />
    </button>
</form>

Ewikis/templates/wiki/edit_form.html
<h1> Edit {{wiki.title}}</h1>
	<form id ="save-form-test" name="Edit" action = "." method ='POST'>
	{% csrf_token %}
	{{textform.as_p}}
	<input type="submit" value = "Save">
</form>